// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Integrador_Senac.Data;

namespace Projeto_Integrador_Senac.Migrations
{
    [DbContext(typeof(Projeto_Integrador_SenacContext))]
    [Migration("20211027053355_Bd_Cliente")]
    partial class Bd_Cliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_Integrador_Senac.Models.Cliente", b =>
                {
                    b.Property<int>("Cliente_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cliente_Celular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("Cliente_Dt_Nasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cliente_Email")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Cliente_Nome")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cliente_Sobrenome")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Cliente_ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Projeto_Integrador_Senac.Models.Produto", b =>
                {
                    b.Property<int>("Produto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Produto_Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Produto_Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Produto_Preco_Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Produto_Preco_Venda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Produto_Quantidade_Estoque")
                        .HasColumnType("int");

                    b.HasKey("Produto_ID");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Projeto_Integrador_Senac.Models.Venda", b =>
                {
                    b.Property<int>("Venda_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cliente_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Cliente_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Produto_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Produto_ID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Venda_Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Venda_Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Venda_Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Venda_ID");

                    b.HasIndex("Cliente_ID1");

                    b.HasIndex("Produto_ID1");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Projeto_Integrador_Senac.Models.Venda", b =>
                {
                    b.HasOne("Projeto_Integrador_Senac.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("Cliente_ID1");

                    b.HasOne("Projeto_Integrador_Senac.Models.Produto", "Produto")
                        .WithMany("Vendas")
                        .HasForeignKey("Produto_ID1");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Projeto_Integrador_Senac.Models.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Projeto_Integrador_Senac.Models.Produto", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
